insert into product values(1, "Goodday", 10, 1, 10, "Britannia", "Biscuits", "Snacks");
insert into product values(2, "Treat", 15, 1, 15, "Parle", "Biscuits", "Snacks");
insert into product values(3, "Parle-G", 5, 1, 5, "Parle", "Biscuits", "Snacks");
insert into product values(4, "Marie Gold", 10, 1, 10, "Britannia", "Biscuits", "Snacks");
insert into product values(5, "Maggi", 12, 1, 12, "Nestle", "Noodels", "Snacks");
insert into product values(6, "Tiger", 5, 1, 5, "Britannia", "Biscuits", "Snacks");
insert into product values(7, "Nice", 15, 1, 15, "Britannia", "Biscuits", "Snacks");
insert into product values(8, "50-50", 10, 1, 10, "Britannia", "Biscuits", "Snacks");
insert into product values(9, "Bourbon", 20, 1, 20, "Britannia", "Biscuits", "Snacks");
insert into product values(10, "Little hearts", 5, 1, 5, "Britannia", "", "Snacks");
insert into product values(11, "Lays", 10, 1, 10, "Pepsi-co", "", "Snacks");
insert into product values(12, "Kurkure", 10, 1, 10, "ITC", "", "Snacks");
insert into product values(13, "Bingo", 10, 1, 10, "ITC", "", "Snacks");
insert into product values(14, "Too yum", 15, 1, 15, "ITC", "Chips", "Snacks");
insert into product values(15, "", , 1, , "", "Chips", "Snacks");
insert into product values(16, "", , 1, , "", "Chips", "Snacks");
insert into product values(17, "", , 1, , "", "Chips", "Snacks");
insert into product values(18, "", , 1, , "", "Chips", "Snacks");
insert into product values(19, "", , 1, , "", "Chips", "Snacks");
insert into product values(20, "", , 1, , "", "Chips", "Snacks");
